project:
  type: website

website:
  title: "ELIXIR-SCO-spatial-transcriptomics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "practicals"
        menu:
          - href: day_1/practical_1/workdir/imaging_based_data_analysis.ipynb
            text: "Practical 1:  Imaging-based data analysis"
          - href: day_2/practical_3/workdir/practical_3.ipynb
            text: "Practical 3: Integration with scRNA-seq"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



