name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - 51-manage-environments
    paths:
      - '**/Dockerfile'
      - '.github/workflows/build_push.yml'

jobs:
  build-practical-1:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

        # Free disk space on the runner
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      # Step 2: Set up Docker Buildx (enables multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        run: |
          echo "Logging into GHCR"
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        shell: bash

      # Step 5: Build and push Docker image to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./day_1/practical_1
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/elixir-europe-training/elixir-sco-spatial-omics:jupyter
