name: Build and Push Docker Image

on:
  push:
    branches:
      - 1-developing-practical-1
    paths:
      - 'day_1/practical_1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (enables multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to v3 to support Node.js 20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./day_1/practical_1
          file: ./day_1/practical_1/Dockerfile
          platforms: linux/amd64
          push: true  
          tags: |
            docker.io/rasoolsnbis/estc_2025/practical_1:latest
