name: Build Docker Image without Push

on:
  push:
    branches:
      - 1-developing-practical-1
    paths:
      - 'day_1/practical_1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (enables multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./day_1/practical_1
          file: ./day_1/practical_1/Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            docker.io/rasoolsnbis/estc_2025/practical_1
